### ISSUE TITLE
not working with current exrm

### ISSUE THREAD

**Issue by schnittchen** [bitwalker/distillery-umbrella-test#6]
I just cloned and ran

```
mix deps.get
mix deps.compile
mix release --verbosity=verbose
```

and it gave me

```
===> Provider (resolve_release) failed with: {error,
                                                     {rlx_prv_release,
                                                      {failed_solve,
                                                       {unreachable_package,
                                                        app_one}}}}
==> Failed to build release. Please fix any errors and try again.

```

**Comment by schnittchen** [comment]
I am trying to bisect this problem, and having problems. Once the release has sucessfully been built, it does not fail on subsequent attempts, even when pointing at a version of exrm that fails on a new checkout. Some stale data is being kept around in my filesystem.

I am doing `mix deps.clean && mix deps.get` between tries, is there a way to grind deeper?

**Comment by kmptkp** [comment]
This issue is still present with elixir 1.3.1, but for those running into it like I just did, here is a workaround. In a fresh clone of this project, do:

mix deps.get
mix compile
mix conform.new
cd apps/master_app
--> edit config/master_app.schema.exs, changing `extends: []` into `extends: [:app_one, :app_two]` on line 52
mix release

You can now run the master_app from inside its directory with:
./rel/master_app/bin/master_app start
